[package]
name = "ndap-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ndap"
path = "src/main.rs"

[dependencies]
ndap-capture = { path = "../crates/capture" }
ndap-protocol = { path = "../crates/protocol" }
ndap-flow = { path = "../crates/flow" }
ndap-detect = { path = "../crates/detect" }
